upgraded rspec-rails since newer rake versions changed.
resolves the following error:

$ rake acts_as_taggable_on_engine:install:migrations
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x0055d4f8455538>