rails 5.1 needs versioned migrations
related travis log:

$ bundle exec rake db:migrate RAILS_ENV=test
/home/travis/build/KatanaCode/blogit/lib/tasks/blogit/doc.rake:9: warning: already initialized constant DOC_FILES
/home/travis/build/KatanaCode/blogit/lib/tasks/blogit/doc.rake:9: warning: previous definition of DOC_FILES was here
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
  class CreateUsers < ActiveRecord::Migration[4.2]
/home/travis/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.0.beta1/lib/active_record/migration.rb:525:in `inherited'
/home/travis/build/KatanaCode/blogit/spec/dummy/db/migrate/20110814091304_create_users.rb:1:in `<top (required)>'